cfn-nag diff

diff --git a/.github/workflows/cfn-nag-diff.yaml b/.github/workflows/cfn-nag-diff.yaml
--- a/.github/workflows/cfn-nag-diff.yaml
+++ b/.github/workflows/cfn-nag-diff.yaml
@@ -36,8 +36,8 @@ jobs:
         if: steps.diff.outputs.diff_files
         run: |
           for file in ${{ steps.diff.outputs.diff_files }}; do
-            cfn_nag_scan --input-path "$file" --deny-list-path ./settings/cfn-nag_deny_list.yml  || {
-            echo "cfn-nag-scan failed for $file"
-            # 必要に応じてエラーログを出力
-          }
-      done
+            cfn_nag_scan --input-path "$file" --deny-list-path ./settings/cfn-nag_deny_list.yml || {
+              echo "cfn-nag-scan failed for $file"
+              # 必要に応じてエラーログを出力
+            }
+          done
